FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json ./

RUN npm ci

COPY --chown=node:node . .

RUN mkdir -p /app/.next && chown node:node /app && chown -R node:node /app/.next

EXPOSE 3000

USER node

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]



