FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=development

ARG DATABASE_URL=postgresql://postgres:postgres@localhost:5432/vitalsync
ENV DATABASE_URL=$DATABASE_URL

COPY package.json package-lock.json ./

RUN npm ci

COPY prisma ./prisma
COPY prisma.config.ts ./
COPY tsconfig.json ./
COPY src ./src

RUN npm run prisma:generate

EXPOSE 5000

USER node

CMD ["npm", "run", "dev"]
