apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vitalsync-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/EbnulAhsan/vitalsync-devops-capstone.git
    targetRevision: dev
    path: kubernetes/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: vitalsync-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
