apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vitalsync-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/EbnulAhsan/vitalsync-devops-capstone.git
    targetRevision: stage
    path: kubernetes/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: vitalsync-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


